"""Build all C4 diagrams + the coverage manifest from a typed IR.

Applies the coverage law deterministically:
  L1 context (1) + L2 container (1) + L3 component (one per OWNED container that
  has components). Owned containers with zero components are recorded in the
  manifest as a logged skip, never silently dropped.

Usage:
    python build.py ir.json --out docs/architecture/<system> [--format plantuml|mermaid|both]
"""
from __future__ import annotations
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import render          # noqa: E402
import validate        # noqa: E402


def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def build(ir, out_dir, fmt="plantuml"):
    do_puml = fmt in ("plantuml", "both")
    do_mmd = fmt in ("mermaid", "both")
    os.makedirs(out_dir, exist_ok=True)
    rows = []  # (level, label, file, status)

    if do_puml:
        _write(os.path.join(out_dir, "context.puml"), render.plantuml_context(ir))
        _write(os.path.join(out_dir, "container.puml"), render.plantuml_container(ir))
    if do_mmd:
        _write(os.path.join(out_dir, "context.mmd"), render.mermaid_context(ir))
        _write(os.path.join(out_dir, "container.mmd"), render.mermaid_container(ir))
    primary = "puml" if do_puml else "mmd"
    rows.append(("L1 Context", ir["system"]["name"], f"context.{primary}", "generated"))
    rows.append(("L2 Container", ir["system"]["name"], f"container.{primary}", "generated"))

    owned = render.owned_containers(ir)
    covered = skipped = 0
    for c in owned:
        label = f"{c['name']} (`{c['id']}`)"
        if not c.get("components"):
            rows.append(("L3 Component", label, "-", "skipped: no components defined"))
            skipped += 1
            continue
        if do_puml:
            _write(os.path.join(out_dir, "components", c["id"] + ".puml"),
                   render.plantuml_component(ir, c["id"]))
        if do_mmd:
            _write(os.path.join(out_dir, "components", c["id"] + ".mmd"),
                   render.mermaid_component(ir, c["id"]))
        rows.append(("L3 Component", label, f"components/{c['id']}.{primary}", "generated"))
        covered += 1

    # copy the IR so validate.py can re-check it independently
    with open(os.path.join(out_dir, "ir.json"), "w", encoding="utf-8") as f:
        json.dump(ir, f, indent=2, ensure_ascii=False)

    _write(os.path.join(out_dir, "index.md"), _manifest(ir, rows, len(owned), covered, skipped, fmt))
    return covered, skipped, len(owned)


def _manifest(ir, rows, denom, covered, skipped, fmt):
    sysn = ir["system"]["name"]
    n_ds = len(ir.get("datastores", []))
    n_ext = len(ir.get("externals", []))
    lines = [
        f"# Architecture — {sysn}",
        "",
        f"Generated by `arch-diagram-gen` from `ir.json` · format: **{fmt}**.",
        "",
        "## Coverage manifest",
        "",
        "| Level | Subject | Diagram | Status |",
        "|-------|---------|---------|--------|",
    ]
    for level, label, file, status in rows:
        lines.append(f"| {level} | {label} | `{file}` | {status} |")
    lines += [
        "",
        f"**Denominator** (C4 coverage law): {denom} owned container(s) -> {denom} L3 diagrams expected.",
        f"**Covered:** {covered}  ·  **Skipped (logged):** {skipped}.",
        "",
        f"_Not decomposed by definition:_ {n_ds} datastore(s) and {n_ext} external system(s) "
        "appear at L1/L2 and as L3 boundary references, but never get their own component diagram.",
        "",
        "> This manifest is the review surface. If a container shows `skipped: no components defined` "
        "but actually has internal structure, add its components to the IR and rebuild.",
    ]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ir")
    ap.add_argument("--out", required=True)
    ap.add_argument("--format", choices=["plantuml", "mermaid", "both"], default="plantuml")
    a = ap.parse_args()
    ir = json.load(open(a.ir, encoding="utf-8"))

    ir_errors = validate.validate_ir(ir)
    if ir_errors:
        print("IR is invalid — fix these before building:")
        for e in ir_errors:
            print(f"  - {e}")
        return 1

    covered, skipped, denom = build(ir, a.out, a.format)
    print(f"Built into {a.out}: context + container + {covered}/{denom} component diagrams "
          f"({skipped} logged skip). Manifest: {os.path.join(a.out, 'index.md')}")
    print("Next: run  python validate.py", a.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
